// Generated by CoffeeScript 1.6.3
(function() {
  this.getStorageData = function(key) {
    return JSON.parse(localStorage[key] || 'null');
  };

  this.setStorageData = function(key, data) {
    return localStorage[key] = JSON.stringify(data);
  };

  this.getCardNames = function(bank) {
    return getStorageData("" + bank + "-cardNames") || [];
  };

  this.setCardNames = function(bank, cardNames) {
    return setStorageData("" + bank + "-cardNames", cardNames);
  };

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    if (!request.command) {
      sendResponse({});
    }
    if (request.command === 'getCardNames') {
      sendResponse(getCardNames(request.bank));
    }
    if (request.command === 'getCardData') {
      return sendResponse(getStorageData("" + request.bank + "-" + request.cardName));
    }
  });

}).call(this);
