// Generated by CoffeeScript 1.6.3
(function() {
  var addString, cardOptionId, createOptionsBind, fillForm, generateCardOptions, golomtFillForm, golomtOptionsAdd, injectFillButton, sendCommand, tdbFillForm, tdbOptionsAdd;

  addString = 'Бөглө';

  cardOptionId = 'autoFillFormCardNames';

  sendCommand = function(name, data, response) {
    data.command = name;
    return chrome.runtime.sendMessage(data, response);
  };

  generateCardOptions = function(cardNames) {
    var $element, $option, cardName, _i, _len;
    $element = $('<select/>').attr('id', cardOptionId);
    $option = $('<option/>').val('').text('Бөглөх картаа сонгоно уу.');
    $element.append($option);
    for (_i = 0, _len = cardNames.length; _i < _len; _i++) {
      cardName = cardNames[_i];
      $option = $('<option/>').val(cardName).text(cardName);
      $element.append($option);
    }
    return $element;
  };

  createOptionsBind = function(source) {
    return $("#" + cardOptionId).on('change', function(ev) {
      fillForm();
      return false;
    });
  };

  tdbOptionsAdd = function() {
    return sendCommand('getCardNames', {
      bank: 'tdb'
    }, function(cardNames) {
      var $cardOptions, $target;
      cardNames = cardNames || [];
      $target = $('#mF');
      $cardOptions = generateCardOptions(cardNames);
      $target.before($cardOptions);
      return createOptionsBind();
    });
  };

  golomtOptionsAdd = function() {
    return sendCommand('getCardNames', {
      bank: 'golomt'
    }, function(cardNames) {
      var $cardOptions, $target;
      cardNames = cardNames || [];
      $target = $('#Table1');
      $cardOptions = generateCardOptions(cardNames);
      $target.before($cardOptions);
      return createOptionsBind();
    });
  };

  golomtFillForm = function() {
    return sendCommand('getCardData', {
      bank: 'golomt',
      cardName: $("#" + cardOptionId).val()
    }, function(cardData) {
      var date;
      cardData = cardData || {};
      $('#cardno').val(cardData['number'] || 'тохируулаагүй байна');
      $('#cardname').val(cardData['holder'] || 'тохируулаагүй байна');
      date = (cardData['expire_date'] || '0/0').split('/');
      $('#edate1').val(date[0]);
      $('#edate2').val(date[1]);
      $('#cardcvv').val(cardData['cvv'] || '');
      $('#cardtel').val(cardData['phone_number'] || 'тохируулаагүй байна');
      return $('#cardmail').val(cardData['email'] || 'тохируулаагүй байна');
    });
  };

  tdbFillForm = function() {
    return sendCommand('getCardData', {
      bank: 'tdb',
      cardName: $("#" + cardOptionId).val()
    }, function(cardData) {
      var date;
      cardData = cardData || {};
      $('input[name="pan"]').val(cardData['number'] || 'тохируулаагүй байна');
      $('input[name="cvv2"]').val(cardData['cvv'] || '');
      $('input[name="fio"]').val(cardData['holder'] || 'тохируулаагүй байна');
      date = (cardData['expire_date'] || '/').split('/');
      $('select[name="expMon"]').val(date[0]);
      $('select[name="ExpYear"]').val("" + date[1][2] + date[1][3]);
      return $('input[name="emailuser"]').val(cardData['email'] || 'тохируулаагүй байна');
    });
  };

  fillForm = function() {
    var host;
    if (!$("#" + cardOptionId).val()) {
      return;
    }
    host = window.location.hostname;
    if (/egolomt\.mn/.test(host)) {
      golomtFillForm();
    }
    if (/bankcard\.mn/.test(host) || /202\.131\.226\.94/.test(host)) {
      return tdbFillForm();
    }
  };

  injectFillButton = function() {
    var host;
    host = window.location.hostname;
    if ($("#" + cardOptionId).length) {
      $("#" + cardOptionId).remove();
    }
    if (/egolomt\.mn/.test(host)) {
      golomtOptionsAdd();
    }
    if (/bankcard\.mn/.test(host) || /202\.131\.226\.94/.test(host)) {
      return tdbOptionsAdd();
    }
  };

  $(function() {
    var timeout;
    timeout = 500;
    return window.setTimeout(injectFillButton, timeout);
  });

}).call(this);
