// Generated by CoffeeScript 1.6.3
(function() {
  var BANKS, background, cardFormTemplate, cardListTemplate, deleteCard, renderCardForm, renderCardList, saveCard,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  background = chrome.extension.getBackgroundPage();

  BANKS = [
    {
      name: 'golomt',
      title: 'Голомт Банк'
    }, {
      name: 'tdb',
      title: 'Худалдаа Хөгжлийн Банк'
    }
  ];

  saveCard = function($form) {
    var bank, cardName, cardNames, data, field, _i, _len, _ref;
    data = {};
    _ref = $form.serializeArray();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      data[field.name] = field.value;
    }
    if (!(data['bank'] && data['name'] && data['number'])) {
      alert('Мэдээллээ бөглөнө үү!');
    }
    bank = data['bank'];
    cardName = data['name'];
    delete data['bank'];
    delete data['name'];
    cardNames = background.getCardNames(bank);
    if (__indexOf.call(cardNames, cardName) < 0) {
      cardNames.push(cardName);
      background.setCardNames(bank, cardNames);
    }
    background.setStorageData("" + bank + "-" + cardName, data);
    renderCardList();
    return renderCardForm();
  };

  deleteCard = function($a) {
    var bank, cardName, cardNames;
    bank = $a.data('bank');
    cardName = $a.data('name');
    if (!confirm("Үнэхээр устгах уу? " + bank + " - " + cardName)) {
      return;
    }
    cardNames = background.getCardNames(bank);
    if (__indexOf.call(cardNames, cardName) >= 0) {
      cardNames.pop(cardName);
      background.setCardNames(bank, cardNames);
    }
    localStorage.removeItem("" + bank + "-" + cardName);
    return renderCardList();
  };

  cardListTemplate = null;

  cardFormTemplate = null;

  renderCardList = function() {
    var bank, banks, card, cardName, cardNames, partials, _i, _j, _len, _len1;
    banks = [];
    for (_i = 0, _len = BANKS.length; _i < _len; _i++) {
      bank = BANKS[_i];
      bank.cards = [];
      cardNames = background.getCardNames(bank.name);
      for (_j = 0, _len1 = cardNames.length; _j < _len1; _j++) {
        cardName = cardNames[_j];
        card = background.getStorageData("" + bank.name + "-" + cardName);
        card['name'] = cardName;
        bank.cards.push(card);
      }
      banks.push(bank);
    }
    partials = {
      card: $('#card-template').html()
    };
    $('#card-list-div').html(cardListTemplate({
      banks: banks
    }, {
      partials: partials
    }));
    $('a.delete-card').on('click', function(event) {
      event.preventDefault();
      return deleteCard($(this));
    });
    return $('a.edit-card').on('click', function(event) {
      event.preventDefault();
      return renderCardForm($(this));
    });
  };

  renderCardForm = function($a) {
    var data;
    data = {
      title: 'Карт нэмэх',
      banks: BANKS
    };
    if ($a) {
      data.bank = $a.data('bank');
      data.name = $a.data('name');
      data.title = 'Карт засах';
      data = $.extend({}, data, background.getStorageData("" + data.bank + "-" + data.name));
    }
    $('#card-form-div').html(cardFormTemplate(data));
    $('a.form-cancel').on('click', function(event) {
      event.preventDefault();
      return renderCardForm();
    });
    return $('form.card-form').on('submit', function(event) {
      event.preventDefault();
      return saveCard($(this));
    });
  };

  $(function() {
    Handlebars.registerHelper('include', function(options) {
      var context;
      context = $.extend({}, this, options.hash);
      return options.fn(context);
    });
    cardListTemplate = Handlebars.compile($('#card-list-template').html());
    cardFormTemplate = Handlebars.compile($('#card-form-template').html());
    renderCardList();
    return renderCardForm();
  });

}).call(this);
